### ISSUE TITLE
Ontology IDs on index page should link to their OBOFoundry.org pages

### ISSUE THREAD

**Issue by jamesaoverton** [lmcmicu/purl-editor#15]
After merging #11 I had second thoughts about the links. Now I think that the first column of ontology IDSPACEs (e.g. "aeo") should link to the ontology's page on OBOFoundry.org (e.g. http://obofoundry.org/ontology/aeo.html) rather than the ontology's OWL file. From there a user can get to the OWL file and lots of other stuff.

Do you agree @jannahastings ?

**Comment by jannahastings** [comment]
Okay, sounds good. 

I used the ontology URL because that was what was specified in the config file alongside the title and description, and not all ontologies have their own website. But the OBOFoundry ontology page is a good alternative, I didn't think of that.
