### ISSUE TITLE
Hide validation error details by default

### ISSUE THREAD

**Issue by jamesaoverton** [lmcmicu/purl-editor#3]
The system currently shows a short, fairly friendly message, and then the details of the JSON Schema and JSON translation of the YAML. Those details can be hidden by default. The user should have to click something to show the details.

I'd suggest implementing this with CSS + JavaScript.

**Comment by jannahastings** [comment]
From review: 
- Make default error message use theme from Bootstrap danger alert message. 
- Also make "Hide Details" link display at the top of the extended message rather than the end.

**Comment by jannahastings** [comment]
@jamesaoverton Can you re-open this issue? I will make a new PR for the rest of the changes.

**Comment by jannahastings** [comment]
@jamesaoverton Never mind it seems I could re-open it myself after I commented :-)

**Comment by jannahastings** [comment]
Additionally, to fix problem that 'idspace: xxx' does not validate if it is the very first line in the text.
